// Import all models to ensure they are registered with Mongoose
import User from './User';
import Role from './Role';
import Product from './Product';
import Order from './Order';
import OrderCounter from './OrderCounter';
import AuditLog from './AuditLog';
import ProductVersion from './ProductVersion';
import AnalyticsEvent from './AnalyticsEvent';
import SearchEvent from './SearchEvent';
import EtsyShop from './EtsyShop';
import EtsyListing from './EtsyListing';
import EtsyOrder from './EtsyOrder';
import EtsyFormField from './EtsyFormField';
// EtsyCacheEntry is imported via etsy-cache.ts when needed
// Removed eRank-specific models (Keyword, Competitor, Trend, ShopHealth)
import SeoQuery from './SeoQuery';
import SeoKeyword from './SeoKeyword';
import SeoProduct from './SeoProduct';
import Blog from './Blog';
import KeywordResearch from './KeywordResearch';
import Review from './Review';
import EmailSubscriber from './EmailSubscriber';
import EmailTracking from './EmailTracking';
import EmailPromoDiscount from './EmailPromoDiscount';
import ProductQuestion from './ProductQA';
import CartAbandonment from './CartAbandonment';
import SavedPaymentMethod from './SavedPaymentMethod';
import SupportTicket from './SupportTicket';
import KnowledgeBase from './KnowledgeBase';
import { ChatMessage, ChatConversation } from './ChatMessage';
import Referral from './Referral';
import ProductBundle from './ProductBundle';
import Subscription from './Subscription';
import PreOrder from './PreOrder';
import StockNotification from './StockNotification';
import PriceAlert from './PriceAlert';
import CustomerAnalytics from './CustomerAnalytics';
import PurchaseAnalytics from './PurchaseAnalytics';
import AbandonedCartAnalytics from './AbandonedCartAnalytics';
import Coupon from './Coupon';

// Export all models for easy importing
export { default as User } from './User';
export { default as Role } from './Role';
export { default as Product } from './Product';
export { default as Order } from './Order';
export { default as OrderCounter } from './OrderCounter';
export { default as AuditLog } from './AuditLog';
export { default as ProductVersion } from './ProductVersion';
export { default as AnalyticsEvent } from './AnalyticsEvent';
export { default as SearchEvent } from './SearchEvent';
export { default as EtsyShop } from './EtsyShop';
export { default as EtsyListing } from './EtsyListing';
export { default as EtsyOrder } from './EtsyOrder';
export { default as EtsyFormField } from './EtsyFormField';
// eRank-specific model exports removed
export { default as SeoQuery } from './SeoQuery';
export { default as SeoKeyword } from './SeoKeyword';
export { default as SeoProduct } from './SeoProduct';
export { default as Blog } from './Blog';
export { default as KeywordResearch } from './KeywordResearch';
export { default as Review } from './Review';
export { default as EmailSubscriber } from './EmailSubscriber';
export { default as EmailTracking } from './EmailTracking';
export { default as EmailPromoDiscount } from './EmailPromoDiscount';
export { default as ProductQuestion } from './ProductQA';
export { ProductAnswer } from './ProductQA';
export { default as CartAbandonment } from './CartAbandonment';
export { default as SavedPaymentMethod } from './SavedPaymentMethod';
export { default as SupportTicket } from './SupportTicket';
export { default as KnowledgeBase } from './KnowledgeBase';
export { ChatMessage, ChatConversation } from './ChatMessage';
export { default as Referral } from './Referral';
export { default as ProductBundle } from './ProductBundle';
export { default as Subscription } from './Subscription';
export { default as PreOrder } from './PreOrder';
export { default as StockNotification } from './StockNotification';
export { default as PriceAlert } from './PriceAlert';
export { default as CustomerAnalytics } from './CustomerAnalytics';
export { default as PurchaseAnalytics } from './PurchaseAnalytics';
export { default as AbandonedCartAnalytics } from './AbandonedCartAnalytics';
export { default as Coupon } from './Coupon';

// Export interfaces
export type { IUser } from './User';
export type { IRole } from './Role';
export type { IProduct } from './Product';
export type { IOrder } from './Order';
export type { IOrderCounter } from './OrderCounter';
export type { IAuditLog } from './AuditLog';
export type { IProductVersion } from './ProductVersion';
export type { IEtsyShop } from './EtsyShop';
export type { IEtsyListing } from './EtsyListing';
export type { IEtsyOrder } from './EtsyOrder';
export type { IEtsyFormField } from './EtsyFormField';
// eRank-specific interface exports removed
export type { ISeoQuery } from './SeoQuery';
export type { ISeoKeyword } from './SeoKeyword';
export type { ISeoProduct } from './SeoProduct';
export type { IKeywordResearch } from './KeywordResearch';
export type { IReview } from './Review';
export type { IEmailSubscriber } from './EmailSubscriber';
export type { IEmailTracking } from './EmailTracking';
export type { IEmailPromoDiscount } from './EmailPromoDiscount';
export type { IQuestion, IAnswer } from './ProductQA';
export type { ICartAbandonment } from './CartAbandonment';
export type { ISavedPaymentMethod } from './SavedPaymentMethod';
export type { ISupportTicket, ITicketMessage } from './SupportTicket';
export type { IKnowledgeBaseArticle } from './KnowledgeBase';
export type { IChatMessage, IChatConversation } from './ChatMessage';
export type { IReferral } from './Referral';
export type { IProductBundle } from './ProductBundle';
export type { ISubscription } from './Subscription';
export type { IPreOrder } from './PreOrder';
export type { IStockNotification } from './StockNotification';
export type { IPriceAlert } from './PriceAlert';
export type { ICustomerAnalytics } from './CustomerAnalytics';
export type { IPurchaseAnalytics } from './PurchaseAnalytics';
export type { IAbandonedCartAnalytics } from './AbandonedCartAnalytics';
export type { ICoupon } from './Coupon';
